name: Notify Discord on pageupdate

on:
  push:
    paths:
      - '**/*.md'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for "pageupdate" commits and notify Discord
        run: |
          commit_message=$(git log -1 --pretty=%B)
          if echo "$commit_message" | grep -qi "pageupdate"; then
            modified_files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '\.md')
            for file in $modified_files; do
              filename=$(basename "$file")
              page_url="https://terraminewiki.github.io/${file%.md}.html"
              content="TerraMineWiki Update !\n$commit_message\n$page_url"
              curl -H "Content-Type: application/json" \
                   -X POST \
                   -d "{\"content\": \"$content\"}" \
                   ${{ secrets.DISCORD_WEBHOOK }}
            done
          fi
